spring:
  application:
    name: wisegrade-spring

  profiles:
    active: dev

server:
  port: 8080
  servlet:
    session:
      timeout: ${APP_SESSION_TIMEOUT:180m}

app:
  exam:
    duration-minutes: ${APP_EXAM_DURATION_MINUTES:90}
